apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluentd

resources:
  - fluentd-daemonset-elasticsearch-rbac.yaml
  - ns.yaml
  - sealed-secrets.yaml

patchesStrategicMerge:
  - patch.yaml
