---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets

---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana

---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
