---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
spec:
  capacity:
    storage: 10Gi
  nfs:
    path: /var/nfs/k8s/raynix.info
    server: 192.168.1.51
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
spec:
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-backup
spec:
  schedule: 0 14 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-tool
              command:
                - /wordpress.sh
                - raynix
                - /wordpress
                - /gcp/idyllic-depth-239301-8ede1c36924a.json
                - raynix-melbourne-backup
