apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon
bases:
  - ../base

resources:
  - ns.yaml
  - ingress.yaml
  - pv.yaml
  - sealed-secret-mastodon.yaml

images:
  - name: tootsuite/mastodon
    newTag: v3.3.0
