---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
spec:
  capacity:
    storage: 10Gi
  nfs:
    path: /var/nfs/k8s/sophix.me
    server: 192.168.1.51
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
spec:
  resources:
    requests:
      storage: 10Gi
