apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-backup
  labels:
    app: cronjob-backup
spec:
  schedule: 0 16 * * *
  jobTemplate:
    spec:
      template:
        metadata:
          name: cronjob-backup
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
          securityContext:
            fsGroup: 991
            runAsGroup: 991
            runAsUser: 991
          restartPolicy: Never
          volumes:
            - name: gcp-sa
              secret:
                secretName: backup-gcp-sa
          containers:
            - name: backup-tool
              image: ghcr.io/raynix/backup:v0.21
              command:
                - /mastodon.sh
                - raynix
                - /gcp/idyllic-depth-239301-8ede1c36924a.json
                - raynix-melbourne-backup

              envFrom:
                - secretRef:
                    name: mastodon
              volumeMounts:
                - name: gcp-sa
                  mountPath: /gcp
