---
apiVersion: batch/v1
kind: Job
metadata:
  name: mastodon-db-migrate
  labels:
    app: mastodon-db-migrate
spec:
  template:
    metadata:
      name: mastodon-db-migrate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      restartPolicy: Never
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: mastodon-assets
        - name: system
          persistentVolumeClaim:
            claimName: mastodon-system
      containers:
        - name: mastodon-db-migrate
          image: "tootsuite/mastodon:v3.3.0"
          command:
            - bundle
            - exec
            - rake
            - db:migrate
          envFrom:
            - secretRef:
                name: mastodon
          volumeMounts:
            - name: assets
              mountPath: /opt/mastodon/public/assets
            - name: system
              mountPath: /opt/mastodon/public/system
