---
apiVersion: batch/v1
kind: Job
metadata:
  name: mastodon-asset-precompile
  labels:
    app: mastodon-asset-precompile
spec:
  template:
    metadata:
      name: mastodon-asset-precompile
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      restartPolicy: Never
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: mastodon-assets
        - name: system
          persistentVolumeClaim:
            claimName: mastodon-system
      containers:
        - name: mastodon-asset-precompile
          image: "tootsuite/mastodon:v3.3.0"
          command:
            - bash
            - -c
            - |
              bundle exec rake assets:precompile && yarn cache clean
          envFrom:
            - secretRef:
                name: mastodon
          volumeMounts:
            - name: assets
              mountPath: /opt/mastodon/public/assets
            - name: system
              mountPath: /opt/mastodon/public/system
