apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml
  - pvc.yaml
  - web-deploy.yaml
  - sidekiq-deploy.yaml
  - streaming-deploy.yaml
  - cronjob-media-remove-orphans.yaml
  - cronjob-backup.yaml
