---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-assets
spec:
  #storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-system
spec:
  #storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
