apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
  - host: domain.name
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 8080
