---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
spec:
  capacity:
    storage: 1Gi
  nfs:
    path: /path/to/nfs/share
    server: nfs.localdomain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
spec:
  resources:
    requests:
      storage: 1Gi
