apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy.yaml
  - pv.yaml
  - pvc.yaml
  - service.yaml
  - redis.yaml
  - ns.yaml
  - cronjob-backup.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
  - name: php-config
    files:
      - php.ini
