apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
spec:
  capacity:
    storage: 10Gi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /dummy/path
    server: localhost
