---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-test-user
  namespace: rbac-test

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rbac-test-user-full-access
  namespace: rbac-test
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rbac-test-user-view
  namespace: rbac-test
subjects:
- kind: ServiceAccount
  name: rbac-test-user
  namespace: rbac-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-test-user-full-access
