apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mandatory.yaml
  - service-nodeport.yaml

patchesStrategicMerge:
  - patch.yaml

images:
  - name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    newName: raynix/nginx-ingress-controller-arm
    newTag: 0.25.1
