# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} #

      # - name: Docker build exif
      #   run: |
      #     cd dockers/exif
      #     docker build -t ghcr.io/raynix/exif:latest .
      #     docker push ghcr.io/raynix/exif:latest

      - name: Build and push backup tool
        uses: docker/build-push-action@v3
        with:
          context: ./dockers/backup
          push: true
          tags: ghcr.io/raynix/backup:v0.${{ github.run_number }}

      # - name: Docker build sideloader
      #   run: |
      #     cd dockers/sideloader
      #     docker build -t ghcr.io/raynix/sideloader:v0.$GITHUB_RUN_NUMBER .
      #     docker tag ghcr.io/raynix/sideloader:v0.$GITHUB_RUN_NUMBER ghcr.io/raynix/sideloader:latest
      #     docker push ghcr.io/raynix/sideloader:v0.$GITHUB_RUN_NUMBER
