# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-20.04 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Docker login
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin


      - name: Docker build exif
        run: |
          cd dockers/exif
          docker build -t ghcr.io/raynix/exif:latest .
          docker push ghcr.io/raynix/exif:latest


      - name: Docker build backup-tool
        run: |
          cd dockers/backup
          docker build -t ghcr.io/raynix/backup:v0.$GITHUB_RUN_NUMBER .
          docker tag ghcr.io/raynix/backup:v0.$GITHUB_RUN_NUMBER ghcr.io/raynix/backup:latest
          docker push ghcr.io/raynix/backup:v0.$GITHUB_RUN_NUMBER


      - name: Docker build sideloader
        run: |
          cd dockers/sideloader
          docker build -t ghcr.io/raynix/sideloader:v0.$GITHUB_RUN_NUMBER .
          docker tag ghcr.io/raynix/sideloader:v0.$GITHUB_RUN_NUMBER ghcr.io/raynix/sideloader:latest
          docker push ghcr.io/raynix/sideloader:v0.$GITHUB_RUN_NUMBER
